// SIM card
#define SECRET_SIM_APN ""
#define SECRET_SIM_PIN ""
// MQTT
#define SECRET_MQTT_SERVER_DOMAIN_NAME ""
#define SECRET_MQTT_SERVER_IP_ADDRESS ""
#define SECRET_MQTT_DEFAULT_TOPIC ""
#define SECRET_MQTT_USER ""
#define SECRET_MQTT_PASSWORD ""
#define SECRET_MQTT_CLIENT_ID ""
#define SECRET_MQTT_PORT 1833